version: "3"
services:
  api:
    image: forecastapi
    ports:
      - "80:7059"
    networks:
      - app-network

  frontend:
    image: forecastapp
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
